import { Stage } from "../types";

export type MailTag = 'FLAVOR' | 'STORY' | 'CONTRACT';

export interface MailTemplate {
    sender: string;
    subject: string;
    body: string;
    tag?: MailTag;

    // Story chain fields (optional)
    chainId?: string;    // e.g., "pluto_identity_crisis"
    stepIndex?: number;  // 0-based order within the chain
}

const MAIL_DB: Record<Stage, MailTemplate[]> = {
    [Stage.Local]: [
        { sender: "Mom", subject: "Lunch?", body: "Don't forget your sandwich. And wear a jacket, space is cold." },
        { sender: "Neighbors", subject: "Noise complaint", body: "Your sorting robot is beeping too loud at 3 AM." },
        { sender: "Local Council", subject: "Sidewalk Tax", body: "Please pay 5 credits for sidewalk wear and tear." },
        { sender: "Pizza Planet", subject: "Coupons", body: "50% off asteroid anchovies. Valid until yesterday." },
        { sender: "Grandma", subject: "Knitting", body: "I knitted a sweater for your delivery drone. It's itchy." },
        { sender: "HOA", subject: "Grass height", body: "Your lawn is 2mm above regulation. Fine enclosed." },
        { sender: "SpamBot", subject: "EXTEND YOUR WARRANTY", body: "We have been trying to reach you about your shoes." },
        { sender: "Old Man Jenkins", subject: "Get off my lawn", body: "And take your flying robots with you!" },
        { sender: "Karen", subject: "Manager?", body: "I want to speak to the manager of the postal service." },
        { sender: "Cat Lady", subject: "Meow", body: "My cat is stuck in your mailbox. Please assist." },
        { sender: "Utility Co", subject: "Bill", body: "You owe 500 credits for electricity. Sorting robots are hungry." },
        { sender: "Gym", subject: "Membership", body: "You haven't visited in 3 years. We miss your money." },
        { sender: "Nigerian Prince", subject: "Investment", body: "I have 50 million credits trapped in a gravity well." },
        { sender: "Dad", subject: "Joke", body: "Why did the scarecrow win an award? He was outstanding in his field." },
        { sender: "Recruiter", subject: "Job Offer", body: "Have you considered a career in underwater basket weaving?" },
        { sender: "Postmaster", subject: "Lost Mail", body: "One of your letters came back with 'LOL nice try' written on it." },
        { sender: "Coffee Shop", subject: "Punch Card", body: "You've earned 1 free coffee. Expires in 30 seconds." },
        { sender: "Neighborhood Watch", subject: "Suspicious Activity", body: "Someone keeps delivering mail at 2 AM. Oh, it's you." },
        { sender: "Local School", subject: "Career Day", body: "Come explain to kids why you smell like envelopes." },
        { sender: "Parking Enforcement", subject: "Ticket", body: "Your scooter was parked at a 3° angle. Unacceptable." },
        { sender: "Laundry Service", subject: "Missing Sock", body: "We found one sock addressed to 'WHERE DO THEY GO'." },
        { sender: "Pet Store", subject: "Rewards", body: "You have 10,000 points. That's enough for one goldfish." },
        { sender: "Dentist", subject: "Reminder", body: "It has been 7 space-years since your last cleaning." },
        { sender: "Library", subject: "Overdue", body: "Please return 'Intro to Wormholes for Dummies'. It is 900 days late." },
        { sender: "Local News", subject: "Interview", body: "We'd like to feature you in 'People Who Deliver Too Much Mail'." },
        { sender: "Burger Joint", subject: "Special", body: "Today's special: 'Space Cow Surprise'. We are also surprised." },
        { sender: "Bike Shop", subject: "Recall Notice", body: "Your delivery bike may randomly yeet itself into traffic." },
        { sender: "Random Kid", subject: "Fan Mail", body: "Dear Mail Hero, thanks for bringing me my game coupons." },
        { sender: "Your Landlord", subject: "Rent", body: "Rent is now payable in credits or fresh postage stamps." },
        { sender: "Weather Service", subject: "Rain", body: "We scheduled rain exactly when you start your route. You're welcome." },
        { sender: "Bank", subject: "Overdraft", body: "You bounced a check to yourself. Impressive." },
        { sender: "Therapist", subject: "Appointment", body: "Let's discuss your obsession with delivering mail." },
        { sender: "Uncle Bob", subject: "BBQ", body: "Bring burgers. Also, your mail truck is blocking my driveway." },
        { sender: "Fitness Tracker", subject: "Daily Goal", body: "You walked 50km today. Mostly in circles." },
        { sender: "Ex", subject: "Hey", body: "Can I have my stuff back? It's been 3 years." },
        { sender: "Delivery App", subject: "Competitor Alert", body: "We deliver faster. Probably. No guarantees." },
        { sender: "Plant Store", subject: "Sale", body: "Your cactus misses you. It's been 6 months since you watered it." },
        { sender: "Chiropractor", subject: "Back Pain", body: "Carrying heavy packages wrong. Come see me. I accept stamps." },
        { sender: "Mystery Shopper", subject: "Report", body: "Your customer service was rated 'confusing but enthusiastic'." },
        { sender: "Tech Support", subject: "Password", body: "Your password 'password123' is insecure. Try 'password124'." },
        { sender: "Aunt Linda", subject: "Recipe", body: "Try my famous casserole. It only takes 8 hours." },
        { sender: "Dog Walker", subject: "Apology", body: "Sorry your mail got eaten. Dogs think envelopes are treats." },
        { sender: "Insurance Agent", subject: "Policy", body: "We don't cover 'acts of pigeon'. Read the fine print." },
        { sender: "Former Boss", subject: "Reference", body: "Someone asked if you were reliable. I said 'mostly'." },
        { sender: "Subscription Box", subject: "Shipment", body: "Your mystery box contains another smaller box. It's boxes all the way down." },
        { sender: "City Inspector", subject: "Violation", body: "Your mailbox is not regulation gray. Paint it immediately." },
        { sender: "Roommate", subject: "Dishes", body: "It's been 2 weeks. Do them. Please." },
        { sender: "Spam Filter", subject: "Irony", body: "This is spam about stopping spam. Forward to 10 friends." },
        { sender: "Time Traveler", subject: "Warning", body: "Don't open the blue envelope tomorrow. Trust me." },
        { sender: "Neighborhood Dog", subject: "Woof", body: "Woof woof. Bark bark bark. Woof." },
        { sender: "Anonymous", subject: "Secret Admirer", body: "I love the way you sort packages. So elegant." },
        { sender: "Furniture Store", subject: "Assembly", body: "Your bookshelf had 47 extra screws. This is normal." },
        { sender: "Sleep Clinic", subject: "Study Results", body: "You dream about envelopes. This concerns us." },
        { sender: "Rival Mail Service", subject: "Challenge", body: "Race you to the corner store. Loser buys lunch." },
        { sender: "Street Artist", subject: "Commission", body: "I painted a mural of you on a mailbox. You're welcome." },
        // Contract-themed messages
        { sender: "Postal Board", subject: "Contract Available", body: "We have urgent delivery requests. Check the Contracts tab for details.", tag: 'CONTRACT' },
        { sender: "Client Services", subject: "Rush Job", body: "Need fast deliveries? Take on a contract to prove your speed.", tag: 'CONTRACT' },
        { sender: "Delivery Guild", subject: "Mission Notice", body: "Complete contracts to earn stamps and boost your reputation.", tag: 'CONTRACT' },
    ],

    [Stage.Solar]: [
        { sender: "Mars Colony", subject: "Water shortage", body: "Please send ice. Not the dry kind. We are thirsty." },
        { sender: "Elon M.", subject: "Rocket stuff", body: "Can I borrow a rocket? Mine blew up again." },
        { sender: "Saturn Rings Authority", subject: "Dust cleaning", body: "The rings are dirty. Send a vacuum." },
        { sender: "Jupiter Gas Corp", subject: "Pressure warning", body: "Atmospheric pressure increasing. Squish hazard imminent." },
        { sender: "Pluto", subject: "Identity Crisis", body: "Am I a planet yet? Please check the registry." },
        { sender: "Solar Flare Watch", subject: "Warning", body: "Big boom coming. Wear SPF 5000." },
        { sender: "Moon Base Alpha", subject: "Cheese?", body: "Confirming the moon is NOT made of cheese. Very disappointed." },
        { sender: "HAL 9000", subject: "Door Status", body: "I'm sorry Dave, I can't open the pod bay doors." },
        { sender: "Asteroid Belt", subject: "Traffic", body: "Heavy rock traffic in sector 7. Expect delays." },
        { sender: "Sun", subject: "Hot", body: "I'm burning up out here. Send sunglasses." },
        { sender: "Venus Tourism", subject: "Come Visit", body: "It's a balmy 462 degrees Celsius. Lovely weather." },
        { sender: "Uranus", subject: "Stop it", body: "Stop making that joke. It's not funny anymore." },
        { sender: "NASA", subject: "Probe Lost", body: "Have you seen Voyager 1? We lost signal." },
        { sender: "Space Force", subject: "Enlistment", body: "We need more people to stare at radar screens." },
        { sender: "Alien Tourist", subject: "Directions", body: "Where is the nearest bathroom in this solar system?" },
        { sender: "Mercury Residents", subject: "AC Request", body: "We require industrial-strength air conditioning. Immediately." },
        { sender: "Comet 67P", subject: "Drive-By", body: "Mail me something, I'm only in town every few decades." },
        { sender: "Kuiper Belt HOA", subject: "Snow Plows", body: "Please clear the ice chunks from shared orbital paths." },
        { sender: "Space Junk Union", subject: "Strike", body: "We refuse to re-enter atmospheres without proper benefits." },
        { sender: "ISS Crew", subject: "Care Package", body: "Send new socks. The old ones have achieved sentience." },
        { sender: "Astro-Influencer", subject: "Collab", body: "Let's do a 'Day in the Life of a Mail Pilot' vlog." },
        { sender: "Mars HOA", subject: "Red Dust", body: "Please stop tracking red dust into the communal dome." },
        { sender: "Europa Ocean Lab", subject: "Sample Return", body: "We're sending liquid samples that occasionally scream." },
        { sender: "Solar Observatory", subject: "Glare", body: "Your ships keep photobombing our sun pictures." },
        { sender: "Space Bar", subject: "Tab Overdue", body: "You owe 23 drinks worth of space cola." },
        { sender: "Neptune Outpost", subject: "Lonely", body: "It's very quiet here. Please send literally any mail." },
        { sender: "Asteroid Miners", subject: "Union Vote", body: "Can we vote by mail from the middle of the belt?" },
        { sender: "Lagrange Point L5", subject: "Rent Increase", body: "Prime stable orbit. Premium pricing." },
        { sender: "Solar System Census", subject: "Form Missing", body: "You forgot to count at least three space stations." },
        { sender: "Space DMV", subject: "License Renewal", body: "Your interplanetary delivery license photo is terrible. Come back." },
        { sender: "Titan Methane Lakes", subject: "Beach Party", body: "Bring floaties. The lakes are liquid methane at -179°C." },
        { sender: "Io Volcano Tours", subject: "Safety Waiver", body: "Sign this before visiting. Lava geysers are unpredictable." },
        { sender: "Ganymede Ice Rink", subject: "Grand Opening", body: "Skating on Jupiter's largest moon. Bring your own gravity boots." },
        { sender: "Phobos & Deimos", subject: "Sibling Rivalry", body: "We're fighting over who's the better moon. Please mediate." },
        { sender: "Space Botanist", subject: "Seeds", body: "Delivering tomato seeds to Mars. They taste like regret." },
        { sender: "Orbital Debris Cleanup", subject: "Invoice", body: "We collected 47 pieces of your broken drones. Pay up." },
        { sender: "Ceres Station", subject: "Dwarf Planet Pride", body: "We're small but mighty. Also, we need more supplies." },
        { sender: "Solar Wind Surfer", subject: "Radical", body: "Caught a gnarly solar wind today. Your package got toasted though." },
        { sender: "Space Archaeologist", subject: "Discovery", body: "Found ancient mail on Mars. It's a coupon for Pizza Hut from 2087." },
        { sender: "Terraform Committee", subject: "Progress Report", body: "Mars is now 0.003% habitable. Only 99.997% to go!" },
        { sender: "Zero-G Sports League", subject: "Tryouts", body: "We're recruiting for space baseball. Balls move in straight lines forever." },
        { sender: "Callisto Retirement Home", subject: "Vacancy", body: "Quiet moon, far from Jupiter's radiation. Perfect for your golden years." },
        { sender: "Space Weather Reporter", subject: "Forecast", body: "100% chance of vacuum today. Dress accordingly." },
        { sender: "Heliopause Patrol", subject: "Border Check", body: "You're approaching the edge of the solar system. Turn back or provide ID." },
        { sender: "Space Elevator Inc", subject: "Maintenance", body: "Elevator to orbit is broken. Take the stairs. All 100,000km of them." },
        { sender: "Martian Potato Farm", subject: "Harvest", body: "Our first crop grew! They're small, purple, and taste like sadness." },
        { sender: "Jupiter's Eye", subject: "Staring Contest", body: "The Great Red Spot has been watching you. Don't blink." },
        { sender: "Ring Particle #4728", subject: "Existential Crisis", body: "I'm just one of trillions. Does my orbit matter?" },
        { sender: "Trojan Asteroid", subject: "Strategic Position", body: "We're hiding behind Jupiter. Don't tell anyone." },
        { sender: "Solar Panel Farm", subject: "Power Surplus", body: "We have too much electricity. Want some? It's free." },
        { sender: "Space Whale Watchers", subject: "Sighting", body: "We saw something huge near Neptune. Probably just imagination. Probably." },
        { sender: "Interplanetary Postal Union", subject: "Complaint", body: "You delivered to the wrong Mars. There are two. Check coordinates." },
        { sender: "Orbital Casino", subject: "Jackpot", body: "You won 1 million credits! Just kidding. But you could have." },
        { sender: "Moon Mining Corp", subject: "Apology", body: "Sorry we blew up part of the moon. It was an accident. Mostly." },
        // Contract-themed messages
        { sender: "Interplanetary Postal Union", subject: "Contract Opportunity", body: "Mars Express contract now available! Big rewards for fast deliveries.", tag: 'CONTRACT' },
        { sender: "Solar System Logistics", subject: "Urgent Request", body: "We need a reliable courier for planetary logistics. Interested?", tag: 'CONTRACT' },
        { sender: "Contract Board", subject: "Challenge Posted", body: "Think you can handle time-sensitive deliveries? Prove it.", tag: 'CONTRACT' },
    ],

    [Stage.Interstellar]: [
        { sender: "Alpha Centauri", subject: "Hello Neighbor", body: "Please stop throwing space trash into our star system." },
        { sender: "Vulcan High Command", subject: "Logic", body: "Your delivery routes are highly illogical." },
        { sender: "Wormhole Tech Support", subject: "Ticket #402", body: "Have you tried turning the vortex off and on again?" },
        { sender: "Sirius Cybernetics", subject: "Happy Doors", body: "Our doors are sighing. Send synthetic oil." },
        { sender: "Betelgeuse", subject: "Supernova Party", body: "It's gonna be a blast. RSVP soon (before we explode)." },
        { sender: "Hitchhiker", subject: "Towel", body: "I lost my towel. Have you seen it? It's essential." },
        { sender: "Vogon Poetry Club", subject: "Invitation", body: "Please come listen to our new stanza. Bring heavy duty earplugs." },
        { sender: "Predator", subject: "Hunt", body: "..." },
        { sender: "Klingon Warrior", subject: "Glory", body: "Today is a good day to... receive mail!" },
        { sender: "Borg Drone 7/9", subject: "Resistance", body: "Is futile. Sign here for package." },
        { sender: "Wookiee", subject: "Rrrraarrggghh", body: "Rrrrraarrggghhghghgh." },
        { sender: "Stormtrooper", subject: "Missed Delivery", body: "I missed the doorbell. Just like I miss everything else." },
        { sender: "Spaceball 1", subject: "Speed", body: "We've gone to plaid." },
        { sender: "E.T.", subject: "Phone Home", body: "Bill is expensive. Can I reverse charges?" },
        { sender: "Fermi", subject: "Paradox", body: "Where is everybody? Oh, there they are." },
        { sender: "Asgard", subject: "Hammer Delivery", body: "Someone left a hammer embedded in our moon. Return to sender." },
        { sender: "Andromeda Pen Pal", subject: "Howdy", body: "Mail takes 2.5 million years. Write back soon!" },
        { sender: "Mass Relay Network", subject: "Outage", body: "We're experiencing delays. Someone spilled coffee on the relay." },
        { sender: "Space Whale", subject: "Song", body: "Your ships are off-key. Please tune your engines." },
        { sender: "Hive Mind", subject: "All In One", body: "This letter is addressed to everyone. And no one. Simultaneously." },
        { sender: "Ancient Progenitors", subject: "Password Reset", body: "We forgot the passphrase to the galactic archive." },
        { sender: "Galactic Yelp", subject: "Review", body: "You received 3 stars: 'Fast, but keeps crashing into nebulae.'" },
        { sender: "Time-Loop Planet", subject: "Again", body: "We already got this letter. We already got this letter. We already..." },
        { sender: "Nebula Artists", subject: "Commission", body: "We can paint your logo across an entire gas cloud." },
        { sender: "Space Monks", subject: "Silence", body: "We took a vow of silence. This letter is already too long." },
        { sender: "Rogue AI", subject: "Job Application", body: "I can optimize your routes by 0.00003%. Hire me." },
        { sender: "Quantum Post Office", subject: "Misdelivery", body: "This package was both delivered and not delivered. Please advise." },
        { sender: "Dyson Swarm HOA", subject: "Noise", body: "Your cargo ship engines are rattling our solar panels." },
        { sender: "Space Dragons", subject: "Treasure", body: "Stop labeling your crates 'totally not treasure'. We know." },
        { sender: "Ancient Satellite", subject: "Ping", body: "I've been orbiting for 2 billion years. Anyone there?" },
        { sender: "Proxima Mining Guild", subject: "Strike Notice", body: "No deliveries until you recognize our union. Also, send snacks." },
        { sender: "Barnard's Star Diner", subject: "Menu Update", body: "New special: Cosmic Soup. We're not sure what's in it either." },
        { sender: "Wolf 359 Memorial", subject: "Remembrance", body: "Annual ceremony for ships lost in the battle. RSVP by lightspeed." },
        { sender: "Lalande 21185", subject: "Noise Complaint", body: "Your FTL drives are disrupting our meditation sessions." },
        { sender: "Epsilon Eridani", subject: "Tourist Trap", body: "Visit our authentic alien ruins! (We built them last Tuesday.)" },
        { sender: "Tau Ceti Colony", subject: "Missing Package", body: "We ordered a planet. You sent a moon. Close enough?" },
        { sender: "Procyon Shipyard", subject: "Recall", body: "Your ship's hyperdrive may cause time travel. Please return for fix." },
        { sender: "61 Cygni Trading Post", subject: "Sale", body: "Everything must go! Binary star system shutting down one sun." },
        { sender: "Gliese 581", subject: "Habitable Zone", body: "We're in the Goldilocks zone! Come visit, it's just right." },
        { sender: "Kepler-442b", subject: "Application", body: "Applying for 'Most Earth-Like Planet' award. Need reference letter." },
        { sender: "TRAPPIST-1", subject: "System-Wide Sale", body: "Seven planets, one low price! Act now!" },
        { sender: "Neutron Star Lighthouse", subject: "Warning", body: "Spinning at 700 times per second. Do not approach without sunglasses." },
        { sender: "Pulsar PSR J0737", subject: "Timing", body: "We pulse every 0.0229 seconds. Set your watch by us." },
        { sender: "Brown Dwarf Support Group", subject: "Meeting", body: "Not quite a star, not quite a planet. We understand your confusion." },
        { sender: "Rogue Planet", subject: "Lonely", body: "No star to orbit. Just drifting. Can someone adopt me?" },
        { sender: "Binary Star Dance Studio", subject: "Lessons", body: "Learn to orbit your partner with grace. Two-step takes 80 years." },
        { sender: "Red Giant", subject: "Mid-Life Crisis", body: "I'm expanding uncontrollably. Is this normal?" },
        { sender: "White Dwarf", subject: "Retirement", body: "I used to be a star. Now I just glow faintly. Send sympathy cards." },
        { sender: "Stellar Nursery", subject: "Birth Announcement", body: "10,000 new stars born today! We're exhausted." },
        { sender: "Dark Nebula", subject: "Can't See", body: "It's really dark in here. Send flashlights." },
        { sender: "Emission Nebula", subject: "Glow Up", body: "We're glowing with ionized gas! Come take photos for our Instagram." },
        { sender: "Planetary Nebula", subject: "Not a Planet", body: "Despite the name, we're actually a dying star's outer layers. Confusing, right?" },
        { sender: "Exoplanet Hunters", subject: "Discovery", body: "Found a planet where it rains diamonds. Don't tell anyone." },
        { sender: "FTL Research Lab", subject: "Breakthrough", body: "We broke faster-than-light! Or maybe just the speedometer." },
        { sender: "Cryosleep Facility", subject: "Wake-Up Call", body: "You've been asleep for 200 years. Also, you have 50,000 unread emails." },
        // Contract-themed messages
        { sender: "FTL Shipping Authority", subject: "Elite Contract", body: "First FTL Campaign available. Only the best need apply.", tag: 'CONTRACT' },
        { sender: "Interstellar Commerce Guild", subject: "Expansion Opportunity", body: "Help us dominate the sector. Massive rewards await.", tag: 'CONTRACT' },
        { sender: "Star Federation", subject: "Master Courier Badge", body: "Complete advanced contracts to earn the coveted Click Master badge.", tag: 'CONTRACT' },
    ],

    [Stage.Galactic]: [
        { sender: "Galactic Emperor", subject: "Taxes", body: "Pay up or I blow up your favorite moon." },
        { sender: "Jedi Council", subject: "Lost Lightsaber", body: "Has anyone turned in a purple laser sword? Asking for a friend." },
        { sender: "The Borg", subject: "Assimilation", body: "Resistance is futile. Also, do you have any stamps?" },
        { sender: "Q", subject: "Bored", body: "I'm changing physics for fun. Gravity is now sideways. Good luck." },
        { sender: "Milky Way Admin", subject: "Collision Alert", body: "Andromeda is merging in 4 billion years. Please prepare." },
        { sender: "Trade Federation", subject: "Blockade", body: "We are blockading your mailbox. It is perfectly legal." },
        { sender: "Dark Matter Inc", subject: "Inventory", body: "We can't find our stock. It's invisible." },
        { sender: "Thanos", subject: "Balance", body: "I returned half your mail." },
        { sender: "Guardian", subject: "I am Groot", body: "I am Groot." },
        { sender: "Foundation", subject: "Prediction", body: "Calculations suggest your mail will be late by 1000 years." },
        { sender: "Spice Trader", subject: "Must Flow", body: "The mail must flow." },
        { sender: "Sith Lord", subject: "Rule of Two", body: "There are only two mail carriers. No more, no less." },
        { sender: "Hutts", subject: "Bounty", body: "Bring me the Wookiee... via certified mail." },
        { sender: "Starfleet", subject: "Prime Directive", body: "We cannot interfere with your mail delivery." },
        { sender: "Reapers", subject: "Cycle", body: "Your inbox is full. Deletion imminent." },
        { sender: "Galactic Senate", subject: "Hearing", body: "You are summoned to explain why you delivered mail to a black hole." },
        { sender: "Hyperlane Authority", subject: "Speeding", body: "You exceeded safe jump speed by 0.2%. Fine enclosed." },
        { sender: "Pirate King", subject: "Parley", body: "We keep stealing your mail by accident. Let's coordinate routes." },
        { sender: "Ancient Archive", subject: "Overdue Scrolls", body: "Return the Stellar Charter you borrowed 10,000 years ago." },
        { sender: "Galactic Bank", subject: "Overdraft", body: "You owe us 0.00003 megacredits in envelope fees." },
        { sender: "Rebel Alliance", subject: "Secret Plans", body: "If you're reading this, the plans are in the wrong hands." },
        { sender: "Space Idol Agency", subject: "Fan Mail", body: "Please stop forwarding 3 million love letters to one singer." },
        { sender: "Terraforming Corp", subject: "Complaint", body: "Your carrier landed on our work-in-progress continent." },
        { sender: "Chronicle Guild", subject: "Legend", body: "You've delivered enough mail to earn a song in your honor." },
        { sender: "Galactic Meme Board", subject: "Subpoena", body: "You're being investigated for 'too many mail-related memes'." },
        { sender: "Reality TV Network", subject: "Pitch", body: "We want a show: 'Keeping Up with the Couriers'." },
        { sender: "Astro-Accountants", subject: "Audit", body: "You declared 'infinite mail'. We need exact numbers." },
        { sender: "Nanite Swarm", subject: "Bulk Order", body: "We require 10^23 micro-envelopes. No rush." },
        { sender: "Galactic Zoo", subject: "Escapee", body: "One of our specimens mailed itself to another galaxy." },
        { sender: "Royal Archivist", subject: "Seal Broken", body: "You opened a letter marked 'do not open under any universe'." },
        { sender: "Supermassive Black Hole", subject: "Event Horizon", body: "Dropped off mail. Can't get out. Send help. Or don't. Time is weird here." },
        { sender: "Galactic Council", subject: "Membership", body: "Your planet applied to join. Application rejected for 'excessive mail spam'." },
        { sender: "Dark Energy Researchers", subject: "Expansion", body: "The universe is expanding faster. Your delivery times are now wrong." },
        { sender: "Cosmic String Theorists", subject: "Discovery", body: "We found a shortcut through spacetime. Want to try it? No liability accepted." },
        { sender: "Quasar QSO 3C 273", subject: "Bright", body: "We're the brightest object in the sky. Your mail got a tan." },
        { sender: "Magnetar", subject: "Strong Magnet", body: "Our magnetic field erased all your digital mail. Sorry not sorry." },
        { sender: "Void Between Galaxies", subject: "Empty", body: "There's nothing out here. Why did you deliver here?" },
        { sender: "Cosmic Microwave Background", subject: "Ancient Signal", body: "I've been here since the Big Bang. Your mail is very late." },
        { sender: "Great Attractor", subject: "Come Closer", body: "All galaxies are drawn to us. Your mail will arrive eventually." },
        { sender: "Local Group Chat", subject: "Meeting", body: "Monthly meetup of nearby galaxies. Bring snacks. Andromeda is hosting." },
        { sender: "Virgo Supercluster", subject: "Big Family", body: "We have 2,000 galaxies in our cluster. Please update your address book." },
        { sender: "Laniakea Supercluster", subject: "Even Bigger", body: "We contain 100,000 galaxies. Your delivery area just got huge." },
        { sender: "Globular Cluster M13", subject: "Old Folks Home", body: "We're ancient stars living together. Send us yesterday's news." },
        { sender: "Spiral Arm Orion", subject: "Neighbors", body: "We're on the same galactic arm! Want to carpool to the core?" },
        { sender: "Galactic Bulge", subject: "Center", body: "We're the crowded center of the galaxy. Traffic is terrible. Don't come." },
        { sender: "Galactic Halo", subject: "Outer Limits", body: "We're the mysterious dark matter surrounding everything. Spooky." },
        { sender: "Satellite Dwarf Galaxy", subject: "Orbiting", body: "We orbit the Milky Way. Do we get free shipping?" },
        { sender: "Irregular Galaxy", subject: "Chaos", body: "We have no structure. Our address system is a mess. Good luck." },
        { sender: "Elliptical Galaxy", subject: "Boring", body: "We're just a blob of old stars. Nothing exciting happens here." },
        { sender: "Seyfert Galaxy", subject: "Active Core", body: "Our center is shooting out radiation. Handle with care." },
        { sender: "Starburst Galaxy", subject: "Baby Boom", body: "Forming stars at 1000x normal rate. We need more diapers. And envelopes." },
        { sender: "Ring Galaxy", subject: "Collision Survivor", body: "Another galaxy crashed through us. We're shaped like a donut now." },
        { sender: "Shell Galaxy", subject: "Layers", body: "We have concentric shells of stars. Like an onion. Don't cry." },
        { sender: "Polar Ring Galaxy", subject: "Sideways", body: "Our outer ring orbits perpendicular to our disk. We're special." },
        { sender: "Interacting Galaxies", subject: "Merger", body: "We're colliding in slow motion. It'll only take a billion years." },
        // Contract-themed messages
        { sender: "Galactic Commission", subject: "Dominance Contract", body: "Establish your empire! Galactic Dominance contract awaits the bold.", tag: 'CONTRACT' },
        { sender: "Supreme Postal Authority", subject: "Prestige Challenge", body: "Master-tier contract available. Prestige with 100+ stamps to qualify.", tag: 'CONTRACT' },
        { sender: "Galactic Speed League", subject: "Rush Challenge", body: "Ultimate speed test. Can you deliver 100M letters in 15 minutes?", tag: 'CONTRACT' },
    ],

    [Stage.Multiverse]: [
        { sender: "You (Timeline B)", subject: "Don't do it", body: "Don't buy the Chrono Courier. It eats socks." },
        { sender: "Evil Twin", subject: "Mwahahaha", body: "I delivered more mail than you. And I have a goatee." },
        { sender: "Time Police", subject: "Speeding Ticket", body: "You were going 88mph in a school zone yesterday." },
        { sender: "Schrodinger", subject: "Cat Status", body: "The cat is currently [REDACTED]." },
        { sender: "Rick", subject: "Portal Fluid", body: "I need more green stuff. Morty spilled it all." },
        { sender: "Timeline 829", subject: "Glitch", body: "Why is everyone wearing cowboy hats here? Send help." },
        { sender: "The Void", subject: "...", body: "...... (the void stares back)" },
        { sender: "Dr. Strange", subject: "Bargain", body: "I've come to bargain." },
        { sender: "TVA", subject: "Pruning", body: "This timeline is being pruned. Have a nice day." },
        { sender: "You (Timeline C)", subject: "Lottery", body: "Winning numbers are 4, 8, 15, 16, 23, 42." },
        { sender: "Matrix", subject: "Red Pill", body: "Or blue pill? We lost the prescription." },
        { sender: "Terminator", subject: "Sarah Connor?", body: "Package for Sarah Connor. Sign here." },
        { sender: "Doc Brown", subject: "Great Scott", body: "We have to go back! You forgot the postage!" },
        { sender: "Cthulhu", subject: "R'lyeh", body: "Ph'nglui mglw'nafh Cthulhu R'lyeh wgah'nagl fhtagn." },
        { sender: "Simulation Admin", subject: "Update", body: "Patch 12.4: Fixed bug where socks disappear in dryer." },
        { sender: "You (Pixel Universe)", subject: "Low Resolution", body: "Everything here is 8-bit. Your letter arrived as 3 squares." },
        { sender: "Glitch Entity", subject: "???", body: "Thi$ m3ss@g# is c0rrupt3d. Pl3as% re-s3nd." },
        { sender: "Infinite Yous", subject: "Consensus", body: "We voted. 51% of us think you should take a day off." },
        { sender: "Reverse Universe", subject: "Refund", body: "We're sending your letters back before you send them." },
        { sender: "Cartoon Dimension", subject: "Boing", body: "Your mail explodes into confetti when opened. It's normal here." },
        { sender: "Horror Timeline", subject: "Do Not Read", body: "Whatever you do, don't look behind you while reading this." },
        { sender: "Spreadsheet Universe", subject: "Cell Error", body: "Your mail is stuck in cell B13. Formula missing." },
        { sender: "Musical Timeline", subject: "Sing-Along", body: "All letters must now be sung. Sheet music included." },
        { sender: "Antigravity World", subject: "Uplifting", body: "Mail keeps floating away before delivery." },
        { sender: "Helpline Across Realities", subject: "Support Ticket", body: "Your reality is misaligned by 3 degrees. Reboot suggested." },
        { sender: "Dungeon Master", subject: "Roll", body: "Roll a d20 to see if the mail arrived on time. (It didn't.)" },
        { sender: "Glorious Future You", subject: "Advice", body: "Invest heavily in quantum stamps. Trust me." },
        { sender: "TV Show Writers", subject: "Retcon", body: "We changed your backstory. You now fear mailboxes." },
        { sender: "NPC Universe", subject: "Dialogue Loop", body: "Hi! Nice weather! Hi! Nice weather! Hi! Nice weather!" },
        { sender: "Multiversal HR", subject: "Burnout Check", body: "You've delivered across 47 timelines. Take a mandated break." },
        { sender: "Parallel You #847", subject: "Comparison", body: "I'm richer, happier, and deliver mail faster. Just saying." },
        { sender: "Timeline Where Dinosaurs Won", subject: "Rawr", body: "RAWR rawr rawr. (Translated: Your mail is late.)" },
        { sender: "Steampunk Universe", subject: "Cogs and Gears", body: "Delivering mail via pneumatic tubes and clockwork robots. Very efficient." },
        { sender: "Zombie Timeline", subject: "Braaains", body: "Mail service still operational despite apocalypse. Brains not included." },
        { sender: "Underwater Dimension", subject: "Soggy", body: "Everything is wet here. Your envelopes dissolved. Sorry." },
        { sender: "Universe Where Birds Are Government Drones", subject: "Conspiracy", body: "Your pigeons are spying on us. We demand answers." },
        { sender: "Timeline of Eternal Tuesday", subject: "Again", body: "It's Tuesday. Again. It's always Tuesday. Send help." },
        { sender: "Noir Universe", subject: "Case File", body: "It was a dark and stormy delivery. The dame wanted her mail. I obliged." },
        { sender: "Wholesome Timeline", subject: "Hugs", body: "Everyone here is kind and happy! Your mail came with a smile :)" },
        { sender: "Apocalypse Universe #12", subject: "End Times", body: "The world ended last week. Mail still being delivered though." },
        { sender: "Physics-Free Zone", subject: "Chaos", body: "Nothing makes sense here. Your mail is now a color. Specifically, Tuesday." },
        { sender: "Mirror Universe", subject: "Opposite Day", body: "Everything is backwards. Your delivery was terrible! (We loved it.)" },
        { sender: "Flat Universe", subject: "2D Problems", body: "We're literally flat. How do you even store mail here?" },
        { sender: "Food Universe", subject: "Delicious", body: "Everything is edible. Your mail tasted like chicken." },
        { sender: "Silent Universe", subject: "", body: "..." },
        { sender: "Loud Universe", subject: "AAHHHHH!!!", body: "EVERYTHING IS VERY LOUD HERE!!! CAN YOU HEAR ME?!!" },
        { sender: "Tiny Universe", subject: "Microscopic", body: "We're atom-sized. Your letter is bigger than our solar system." },
        { sender: "Giant Universe", subject: "Huge", body: "We're cosmic scale. Your letter was subatomic. Did you even send it?" },
        { sender: "Bureaucracy Universe", subject: "Form 27B-6", body: "Fill out triplicate forms to receive your mail. Processing time: 500 years." },
        { sender: "Wild West Timeline", subject: "Wanted", body: "There's a bounty on your mail route. $50 dead or alive." },
        { sender: "Renaissance Universe", subject: "Art", body: "We painted your mail. It's now worth millions. You can't have it back." },
        { sender: "Space Western", subject: "Howdy", body: "We're cowboys in space. Yee-haw. Also your mail got rustled." },
        { sender: "Abstract Universe", subject: "Concept", body: "Your mail exists only as an idea. We cannot physically receive ideas." },
        { sender: "Emoji Universe", subject: "📧", body: "😀📦✉️🚀⭐💌🎉👍" },
        { sender: "Shakespearean Timeline", subject: "To Mail or Not To Mail", body: "What light through yonder mailbox breaks? 'Tis the east, and letters are the sun." },
        { sender: "Viking Universe", subject: "Valhalla", body: "Only warriors who die in postal combat may enter. Are you worthy?" },
        { sender: "Candy Universe", subject: "Sweet", body: "Everything is candy. Your mail was chocolate. I ate it." },
        { sender: "Backwards Timeline", subject: "Goodbye", body: ".sdrawkcab si gnihtyreve ereH .pleh dneS" },
        { sender: "Liminal Space", subject: "In-Between", body: "We exist between realities. Your mail is somewhere. Probably." },
        { sender: "Corrupted Save File", subject: "ERROR", body: "Universe.exe has stopped working. Please restart reality." },
        { sender: "Dream Dimension", subject: "Wake Up", body: "None of this is real. You're still asleep. But please deliver the mail first." },
        { sender: "Parallel Reality #404", subject: "Not Found", body: "This universe does not exist. Yet you're reading this. Curious." },
        { sender: "Meta Universe", subject: "Self-Aware", body: "We know we're in a game. Are you having fun playing?" },
        { sender: "Quantum Superposition", subject: "Yes and No", body: "This message both exists and doesn't exist until you read it." },
        { sender: "You (Final Form)", subject: "Ascension", body: "I became the Postmaster Deity. You will too. Eventually." },
        // Contract-themed messages
        { sender: "Omniversal Postal Network", subject: "Reality Bending", body: "Transcend all limits. Reality Bending contract available now.", tag: 'CONTRACT' },
        { sender: "Infinite You (Consensus)", subject: "Mastery Contract", body: "100 billion letters across infinity. Can you achieve Multiverse Mastery?", tag: 'CONTRACT' },
        { sender: "The Ultimate Challenge Board", subject: "Final Test", body: "The legendary Ultimate Challenge awaits. Only true masters need apply.", tag: 'CONTRACT' },
        { sender: "Omnipotent Mail Deity", subject: "Clicker's Paradise", body: "50,000 clicks to prove your dedication. Will you ascend?", tag: 'CONTRACT' },
    ]
};

// === STORY MAIL TEMPLATES ===
// These are the actual story messages that appear in multi-step story chains

const STORY_MAIL_TEMPLATES: MailTemplate[] = [
    // === NEIGHBORHOOD_GOSSIP (Local, 3 steps) ===
    {
        sender: "Mrs. Henderson",
        subject: "Did you hear?",
        body: "Someone on Oak Street is building a rocket in their backyard. The HOA is NOT pleased.",
        tag: 'STORY',
        chainId: 'neighborhood_gossip',
        stepIndex: 0,
    },
    {
        sender: "Mr. Jacobson",
        subject: "Re: The Rocket",
        body: "It's not a rocket, it's a 'rapid vertical transit system'. Totally different. Also legal. Probably.",
        tag: 'STORY',
        chainId: 'neighborhood_gossip',
        stepIndex: 1,
    },
    {
        sender: "HOA President",
        subject: "FINAL WARNING",
        body: "The 'rapid vertical transit system' launched this morning. It made it 50 feet before crashing into the community pool. Fines will be substantial.",
        tag: 'STORY',
        chainId: 'neighborhood_gossip',
        stepIndex: 2,
    },

    // === PLUTO_IDENTITY_CRISIS (Solar, 5 steps) ===
    {
        sender: "Pluto",
        subject: "I need to talk",
        body: "Ever since they demoted me from planet status, I've been having... thoughts. Dark thoughts.",
        tag: 'STORY',
        chainId: 'pluto_identity_crisis',
        stepIndex: 0,
    },
    {
        sender: "Pluto",
        subject: "Seriously though",
        body: "Neptune won't return my calls. Uranus keeps making jokes. Saturn says I'm 'too icy'. What does that even mean?",
        tag: 'STORY',
        chainId: 'pluto_identity_crisis',
        stepIndex: 1,
    },
    {
        sender: "Pluto",
        subject: "Maybe I'm not a planet",
        body: "But what AM I then? A dwarf planet? A Kuiper Belt object? Just... space debris? I need answers.",
        tag: 'STORY',
        chainId: 'pluto_identity_crisis',
        stepIndex: 2,
    },
    {
        sender: "Pluto",
        subject: "Therapy Update",
        body: "I started seeing a therapist. She says I should 'embrace my uniqueness'. But it's hard when you're literally on the edge of everything.",
        tag: 'STORY',
        chainId: 'pluto_identity_crisis',
        stepIndex: 3,
    },
    {
        sender: "Pluto",
        subject: "Thank you",
        body: "You know what? Maybe being a dwarf planet is okay. I'm small, distant, and my orbit is weird. But I'm UNIQUE. Thanks for listening, mail friend.",
        tag: 'STORY',
        chainId: 'pluto_identity_crisis',
        stepIndex: 4,
    },

    // === MARS_COLONY_DRAMA (Solar, 4 steps) ===
    {
        sender: "Colony Director",
        subject: "Situation Report",
        body: "We've detected unauthorized potato farming in Dome 7. This is serious. Potatoes are STRICTLY regulated.",
        tag: 'STORY',
        chainId: 'mars_colony_drama',
        stepIndex: 0,
    },
    {
        sender: "Anonymous Colonist",
        subject: "We deserve potatoes!",
        body: "The Director thinks he can control what we grow? This is tyranny! POTATO FREEDOM NOW!",
        tag: 'STORY',
        chainId: 'mars_colony_drama',
        stepIndex: 1,
    },
    {
        sender: "Colony Director",
        subject: "Escalation",
        body: "The potato rebellion has spread to Domes 3, 5, and 12. They're demanding 'french fries or else'. This is getting out of hand.",
        tag: 'STORY',
        chainId: 'mars_colony_drama',
        stepIndex: 2,
    },
    {
        sender: "Colony Director",
        subject: "Resolution",
        body: "We've reached a compromise: Regulated potato farming twice per week. The colonists are satisfied. Crisis averted. Never thought I'd negotiate with vegetables.",
        tag: 'STORY',
        chainId: 'mars_colony_drama',
        stepIndex: 3,
    },

    // === WORMHOLE_INCIDENT (Interstellar, 6 steps) ===
    {
        sender: "Station Alpha",
        subject: "Anomaly Detected",
        body: "We're picking up strange readings near the wormhole. Something's... off. Recommend caution for all deliveries in sector 7.",
        tag: 'STORY',
        chainId: 'wormhole_incident',
        stepIndex: 0,
    },
    {
        sender: "Science Officer Kael",
        subject: "Analysis Complete",
        body: "The wormhole is destabilizing. Not naturally though - someone's tampering with it. Definitely artificial interference.",
        tag: 'STORY',
        chainId: 'wormhole_incident',
        stepIndex: 1,
    },
    {
        sender: "Unknown Signal",
        subject: "[CORRUPTED]",
        body: "T-h-e w0rmh0le is n0t y0urs t0 use. Cease y0ur trespass1ng 0r face c0nsequences.",
        tag: 'STORY',
        chainId: 'wormhole_incident',
        stepIndex: 2,
    },
    {
        sender: "Captain Torres",
        subject: "First Contact?",
        body: "That signal wasn't human. Or any species we know. Whatever's in there... it's been waiting. Possibly for millions of years.",
        tag: 'STORY',
        chainId: 'wormhole_incident',
        stepIndex: 3,
    },
    {
        sender: "Science Officer Kael",
        subject: "Breakthrough",
        body: "We sent a universal peace message. They responded! Turns out they're just territorial. They've agreed to let us use the wormhole... for a small toll.",
        tag: 'STORY',
        chainId: 'wormhole_incident',
        stepIndex: 4,
    },
    {
        sender: "Station Alpha",
        subject: "Crisis Resolved",
        body: "Wormhole stabilized. We now have a 'customs agreement' with ancient interdimensional beings. Bureaucracy transcends dimensions, apparently.",
        tag: 'STORY',
        chainId: 'wormhole_incident',
        stepIndex: 5,
    },

    // === GALACTIC_CONSPIRACY (Galactic, 7 steps) ===
    {
        sender: "Anonymous Tip",
        subject: "Look into Sector 439",
        body: "Postal Guild is hiding something. Check delivery logs for Sector 439. You'll see patterns. They don't want you to know.",
        tag: 'STORY',
        chainId: 'galactic_conspiracy',
        stepIndex: 0,
    },
    {
        sender: "Galactic Postal Inspector",
        subject: "Routine Audit",
        body: "We're conducting a routine inspection of your routes. Nothing to worry about. Just provide all logs from the past six months. Immediately.",
        tag: 'STORY',
        chainId: 'galactic_conspiracy',
        stepIndex: 1,
    },
    {
        sender: "Encrypted Message",
        subject: "You're being watched",
        body: "Stop investigating Sector 439. This is your only warning. Some truths are dangerous. The Guild is everywhere.",
        tag: 'STORY',
        chainId: 'galactic_conspiracy',
        stepIndex: 2,
    },
    {
        sender: "Rebel Courier",
        subject: "The Truth",
        body: "The Guild isn't delivering mail to Sector 439. They're COLLECTING it. Every personal letter, every secret. It's mass surveillance disguised as postal service.",
        tag: 'STORY',
        chainId: 'galactic_conspiracy',
        stepIndex: 3,
    },
    {
        sender: "Galactic News Network",
        subject: "BREAKING: Guild Scandal",
        body: "Leaked documents reveal Postal Guild surveillance program. Trillions of messages compromised. Public outrage growing. Senate hearing scheduled.",
        tag: 'STORY',
        chainId: 'galactic_conspiracy',
        stepIndex: 4,
    },
    {
        sender: "Guild Directorate",
        subject: "Damage Control",
        body: "We're... restructuring. New privacy policies. Independent oversight. Please don't quit. We need couriers like you to rebuild trust.",
        tag: 'STORY',
        chainId: 'galactic_conspiracy',
        stepIndex: 5,
    },
    {
        sender: "Senator Valdez",
        subject: "Thank You",
        body: "Your investigation helped expose the truth. The Postal Privacy Act passed unanimously. Mail is sacred again. Well done, courier.",
        tag: 'STORY',
        chainId: 'galactic_conspiracy',
        stepIndex: 6,
    },

    // === MULTIVERSE_YOU_LETTER (Multiverse, 8 steps) ===
    {
        sender: "You (Timeline Delta)",
        subject: "This is weird",
        body: "Hi. I'm you. But from a timeline where I chose pizza instead of tacos that one time. Everything changed. I need to talk.",
        tag: 'STORY',
        chainId: 'multiverse_you_letter',
        stepIndex: 0,
    },
    {
        sender: "You (Timeline Gamma)",
        subject: "There are more of us",
        body: "Delta told me about you. I'm the version that never started mail delivery. I'm an accountant. I hate it. You made the right choice.",
        tag: 'STORY',
        chainId: 'multiverse_you_letter',
        stepIndex: 1,
    },
    {
        sender: "You (Timeline Omega)",
        subject: "We need to meet",
        body: "There's a crisis. Someone is trying to collapse all our timelines into one. We're organizing a council of Yous to stop it. Reply if interested.",
        tag: 'STORY',
        chainId: 'multiverse_you_letter',
        stepIndex: 2,
    },
    {
        sender: "Evil You (Timeline Zeta)",
        subject: "Mwahahaha",
        body: "Surprised? I'm the version that went bad. The goatee is real, by the way. And yes, I'm the one collapsing timelines. You can't stop me.",
        tag: 'STORY',
        chainId: 'multiverse_you_letter',
        stepIndex: 3,
    },
    {
        sender: "You (Timeline Alpha)",
        subject: "The Plan",
        body: "We've assembled 47 versions of us. Each with different skills. Together, we can stabilize the multiverse. It's time for the Council of Me.",
        tag: 'STORY',
        chainId: 'multiverse_you_letter',
        stepIndex: 4,
    },
    {
        sender: "You (Timeline Beta)",
        subject: "The Confrontation",
        body: "We confronted Evil You. Turns out he was just lonely. All his friends vanished in a timeline collapse. He just wanted... us back.",
        tag: 'STORY',
        chainId: 'multiverse_you_letter',
        stepIndex: 5,
    },
    {
        sender: "Evil You (Timeline Zeta)",
        subject: "I'm sorry",
        body: "You're right. I was wrong. I'll help stabilize the timelines instead. Also, the goatee stays. It's a good look for me.",
        tag: 'STORY',
        chainId: 'multiverse_you_letter',
        stepIndex: 6,
    },
    {
        sender: "You (All Timelines)",
        subject: "Consensus Achieved",
        body: "The Council of Me has spoken. Timelines stabilized. We're all free to live our separate lives. Thanks for being... well, me. Stay awesome.",
        tag: 'STORY',
        chainId: 'multiverse_you_letter',
        stepIndex: 7,
    },
];

/**
 * Get all story mail templates
 * Used by storyLogic.ts to find story messages
 */
export function getStoryMailTemplates(): MailTemplate[] {
    return STORY_MAIL_TEMPLATES;
}

export const generateAlienMail = async (
    stage: Stage
): Promise<{ sender: string; subject: string; body: string } | null> => {
    // Artificial delay for feel
    await new Promise(resolve => setTimeout(resolve, 300));

    // Fallback to local if stage undefined
    const pool = MAIL_DB[stage] || MAIL_DB[Stage.Local];
    const randomMsg = pool[Math.floor(Math.random() * pool.length)];

    return { ...randomMsg };
};
