/**
 * Contracts Configuration
 *
 * This file contains all numeric values for contract definitions including
 * target values, rewards, time limits, and unlock conditions.
 *
 * Note: Contract objectives and descriptions remain in contracts.ts as they
 * involve structural logic, not just numbers.
 */

// === LOCAL TIER CONTRACTS ===

// Neighborhood Rush
export const CONTRACT_NEIGHBORHOOD_RUSH_TARGET = 10_000;
export const CONTRACT_NEIGHBORHOOD_RUSH_REWARD_CREDITS = 5000;
export const CONTRACT_NEIGHBORHOOD_RUSH_REWARD_RP = 50;

// Click Frenzy
export const CONTRACT_CLICK_FRENZY_TARGET = 500;
export const CONTRACT_CLICK_FRENZY_REWARD_CREDITS = 2000;
export const CONTRACT_CLICK_FRENZY_REWARD_RP = 25;

// Speed Delivery
export const CONTRACT_SPEED_DELIVERY_TARGET = 5000;
export const CONTRACT_SPEED_DELIVERY_TIME_LIMIT_SECONDS = 180; // 3 minutes
export const CONTRACT_SPEED_DELIVERY_UNLOCK_LETTERS = 5000;
export const CONTRACT_SPEED_DELIVERY_REWARD_CREDITS = 10_000;
export const CONTRACT_SPEED_DELIVERY_REWARD_STAMPS = 1;
export const CONTRACT_SPEED_DELIVERY_REWARD_RP = 100;

// Local Expansion
export const CONTRACT_LOCAL_EXPANSION_TARGET = 50_000;
export const CONTRACT_LOCAL_EXPANSION_UNLOCK_LETTERS = 10_000;
export const CONTRACT_LOCAL_EXPANSION_REWARD_CREDITS = 25_000;
export const CONTRACT_LOCAL_EXPANSION_REWARD_RP = 200;

// Early Automation
export const CONTRACT_EARLY_AUTOMATION_TARGET_LPS = 50;
export const CONTRACT_EARLY_AUTOMATION_UNLOCK_LETTERS = 20_000;
export const CONTRACT_EARLY_AUTOMATION_REWARD_CREDITS = 30_000;
export const CONTRACT_EARLY_AUTOMATION_REWARD_RP = 250;

// === SOLAR TIER CONTRACTS ===

// Mars Express
export const CONTRACT_MARS_EXPRESS_TARGET_LPS = 500;
export const CONTRACT_MARS_EXPRESS_REWARD_CREDITS = 250_000;
export const CONTRACT_MARS_EXPRESS_REWARD_RP = 500;

// Planetary Logistics
export const CONTRACT_PLANETARY_LOGISTICS_TARGET = 1_000_000;
export const CONTRACT_PLANETARY_LOGISTICS_REWARD_STAMPS = 1;
export const CONTRACT_PLANETARY_LOGISTICS_REWARD_RP = 1000;

// Solar Challenge
export const CONTRACT_SOLAR_CHALLENGE_TARGET = 500_000;
export const CONTRACT_SOLAR_CHALLENGE_TIME_LIMIT_SECONDS = 300; // 5 minutes
export const CONTRACT_SOLAR_CHALLENGE_UNLOCK_LETTERS = 250_000;
export const CONTRACT_SOLAR_CHALLENGE_REWARD_CREDITS = 1_000_000;
export const CONTRACT_SOLAR_CHALLENGE_REWARD_STAMPS = 2;
export const CONTRACT_SOLAR_CHALLENGE_REWARD_RP = 2500;

// Outer Planets
export const CONTRACT_OUTER_PLANETS_TARGET = 5_000_000;
export const CONTRACT_OUTER_PLANETS_UNLOCK_LETTERS = 1_000_000;
export const CONTRACT_OUTER_PLANETS_REWARD_CREDITS = 2_500_000;
export const CONTRACT_OUTER_PLANETS_REWARD_STAMPS = 1;
export const CONTRACT_OUTER_PLANETS_REWARD_RP = 3000;

// Solar Production
export const CONTRACT_SOLAR_PRODUCTION_TARGET_LPS = 5000;
export const CONTRACT_SOLAR_PRODUCTION_UNLOCK_LETTERS = 2_000_000;
export const CONTRACT_SOLAR_PRODUCTION_REWARD_CREDITS = 5_000_000;
export const CONTRACT_SOLAR_PRODUCTION_REWARD_RP = 5000;

// === INTERSTELLAR TIER CONTRACTS ===

// First FTL Campaign
export const CONTRACT_FTL_CAMPAIGN_TARGET_LPS = 500_000;
export const CONTRACT_FTL_CAMPAIGN_REWARD_STAMPS = 3;
export const CONTRACT_FTL_CAMPAIGN_REWARD_RP = 5000;

// Interstellar Expansion
export const CONTRACT_INTERSTELLAR_EXPANSION_TARGET = 1_000_000_000;
export const CONTRACT_INTERSTELLAR_EXPANSION_REWARD_CREDITS = 500_000_000;
export const CONTRACT_INTERSTELLAR_EXPANSION_REWARD_STAMPS = 2;
export const CONTRACT_INTERSTELLAR_EXPANSION_REWARD_RP = 10_000;

// Interstellar Velocity
export const CONTRACT_INTERSTELLAR_VELOCITY_TARGET = 100_000_000;
export const CONTRACT_INTERSTELLAR_VELOCITY_TIME_LIMIT_SECONDS = 180; // 3 minutes
export const CONTRACT_INTERSTELLAR_VELOCITY_UNLOCK_LETTERS = 50_000_000;
export const CONTRACT_INTERSTELLAR_VELOCITY_REWARD_CREDITS = 250_000_000;
export const CONTRACT_INTERSTELLAR_VELOCITY_REWARD_STAMPS = 3;
export const CONTRACT_INTERSTELLAR_VELOCITY_REWARD_RP = 8000;

// Quantum Network Challenge
export const CONTRACT_QUANTUM_NETWORK_TARGET_LPS = 2_000_000;
export const CONTRACT_QUANTUM_NETWORK_REWARD_STAMPS = 3;
export const CONTRACT_QUANTUM_NETWORK_REWARD_RP = 12_000;

// Click Master
export const CONTRACT_CLICK_MASTER_TARGET_CLICKS = 10_000;
export const CONTRACT_CLICK_MASTER_UNLOCK_CLICKS = 2000;
export const CONTRACT_CLICK_MASTER_REWARD_STAMPS = 2;
export const CONTRACT_CLICK_MASTER_REWARD_RP = 5000;

// Sector Control
export const CONTRACT_SECTOR_CONTROL_TARGET = 5_000_000_000;
export const CONTRACT_SECTOR_CONTROL_UNLOCK_LETTERS = 500_000_000;
export const CONTRACT_SECTOR_CONTROL_REWARD_CREDITS = 2_000_000_000;
export const CONTRACT_SECTOR_CONTROL_REWARD_STAMPS = 3;
export const CONTRACT_SECTOR_CONTROL_REWARD_RP = 15_000;

// === GALACTIC TIER CONTRACTS ===

// Galactic Dominance
export const CONTRACT_GALACTIC_DOMINANCE_TARGET_LPS = 100_000_000;
export const CONTRACT_GALACTIC_DOMINANCE_REWARD_STAMPS = 5;
export const CONTRACT_GALACTIC_DOMINANCE_REWARD_RP = 25_000;

// Galactic Monopoly
export const CONTRACT_GALACTIC_MONOPOLY_TARGET = 500_000_000_000;
export const CONTRACT_GALACTIC_MONOPOLY_REWARD_CREDITS = 100_000_000_000;
export const CONTRACT_GALACTIC_MONOPOLY_REWARD_STAMPS = 6;
export const CONTRACT_GALACTIC_MONOPOLY_REWARD_RP = 30_000;

// Prestige Master
export const CONTRACT_PRESTIGE_MASTER_TARGET_STAMPS = 250;
export const CONTRACT_PRESTIGE_MASTER_UNLOCK_PRESTIGES = 5;
export const CONTRACT_PRESTIGE_MASTER_REWARD_STAMPS = 10;
export const CONTRACT_PRESTIGE_MASTER_REWARD_RP = 50_000;

// Galactic Rush
export const CONTRACT_GALACTIC_RUSH_TARGET = 50_000_000_000;
export const CONTRACT_GALACTIC_RUSH_TIME_LIMIT_SECONDS = 300; // 5 minutes
export const CONTRACT_GALACTIC_RUSH_UNLOCK_LETTERS = 10_000_000_000;
export const CONTRACT_GALACTIC_RUSH_REWARD_CREDITS = 100_000_000_000;
export const CONTRACT_GALACTIC_RUSH_REWARD_STAMPS = 8;
export const CONTRACT_GALACTIC_RUSH_REWARD_RP = 75_000;

// Wormhole Efficiency
export const CONTRACT_WORMHOLE_EFFICIENCY_TARGET_LPS = 500_000_000;
export const CONTRACT_WORMHOLE_EFFICIENCY_REWARD_STAMPS = 7;
export const CONTRACT_WORMHOLE_EFFICIENCY_REWARD_RP = 100_000;

// Galactic Sprint
export const CONTRACT_GALACTIC_SPRINT_TARGET = 20_000_000_000;
export const CONTRACT_GALACTIC_SPRINT_TIME_LIMIT_SECONDS = 120; // 2 minutes
export const CONTRACT_GALACTIC_SPRINT_UNLOCK_LETTERS = 50_000_000_000;
export const CONTRACT_GALACTIC_SPRINT_REWARD_CREDITS = 50_000_000_000;
export const CONTRACT_GALACTIC_SPRINT_REWARD_STAMPS = 6;
export const CONTRACT_GALACTIC_SPRINT_REWARD_RP = 60_000;

// Click Galaxy
export const CONTRACT_CLICK_GALAXY_TARGET_CLICKS = 50_000;
export const CONTRACT_CLICK_GALAXY_UNLOCK_CLICKS = 15_000;
export const CONTRACT_CLICK_GALAXY_REWARD_STAMPS = 5;
export const CONTRACT_CLICK_GALAXY_REWARD_RP = 40_000;

// === MULTIVERSE TIER CONTRACTS ===

// Reality Bending
export const CONTRACT_REALITY_BENDING_TARGET_LPS = 5_000_000_000;
export const CONTRACT_REALITY_BENDING_REWARD_STAMPS = 10;
export const CONTRACT_REALITY_BENDING_REWARD_RP = 250_000;

// Multiverse Mastery
export const CONTRACT_MULTIVERSE_MASTERY_TARGET = 10_000_000_000_000; // 10 trillion
export const CONTRACT_MULTIVERSE_MASTERY_REWARD_STAMPS = 15;
export const CONTRACT_MULTIVERSE_MASTERY_REWARD_RP = 500_000;

// Timeline Mastery
export const CONTRACT_TIMELINE_MASTERY_TARGET_LPS = 20_000_000_000;
export const CONTRACT_TIMELINE_MASTERY_REWARD_STAMPS = 18;
export const CONTRACT_TIMELINE_MASTERY_REWARD_RP = 750_000;

// Omnipotent Clicker
export const CONTRACT_OMNIPOTENT_CLICKER_TARGET_CLICKS = 100_000;
export const CONTRACT_OMNIPOTENT_CLICKER_UNLOCK_CLICKS = 25_000;
export const CONTRACT_OMNIPOTENT_CLICKER_REWARD_STAMPS = 12;
export const CONTRACT_OMNIPOTENT_CLICKER_REWARD_RP = 400_000;

// Dimensional Sprint
export const CONTRACT_DIMENSIONAL_SPRINT_TARGET = 500_000_000_000;
export const CONTRACT_DIMENSIONAL_SPRINT_TIME_LIMIT_SECONDS = 180; // 3 minutes
export const CONTRACT_DIMENSIONAL_SPRINT_UNLOCK_LETTERS = 1_000_000_000_000; // 1 trillion
export const CONTRACT_DIMENSIONAL_SPRINT_REWARD_CREDITS = 1_000_000_000_000; // 1 trillion
export const CONTRACT_DIMENSIONAL_SPRINT_REWARD_STAMPS = 20;
export const CONTRACT_DIMENSIONAL_SPRINT_REWARD_RP = 800_000;

// Infinity Engine
export const CONTRACT_INFINITY_ENGINE_TARGET_LPS = 50_000_000_000;
export const CONTRACT_INFINITY_ENGINE_UNLOCK_LETTERS = 5_000_000_000_000; // 5 trillion
export const CONTRACT_INFINITY_ENGINE_REWARD_STAMPS = 22;
export const CONTRACT_INFINITY_ENGINE_REWARD_RP = 900_000;

// Cosmic Singularity
export const CONTRACT_COSMIC_SINGULARITY_TARGET = 50_000_000_000_000; // 50 trillion
export const CONTRACT_COSMIC_SINGULARITY_UNLOCK_LETTERS = 10_000_000_000_000; // 10 trillion
export const CONTRACT_COSMIC_SINGULARITY_REWARD_STAMPS = 30;
export const CONTRACT_COSMIC_SINGULARITY_REWARD_RP = 1_500_000;

// Temporal Acceleration
export const CONTRACT_TEMPORAL_ACCELERATION_TARGET = 2_000_000_000_000; // 2 trillion
export const CONTRACT_TEMPORAL_ACCELERATION_TIME_LIMIT_SECONDS = 300; // 5 minutes
export const CONTRACT_TEMPORAL_ACCELERATION_UNLOCK_LETTERS = 5_000_000_000_000; // 5 trillion
export const CONTRACT_TEMPORAL_ACCELERATION_REWARD_CREDITS = 5_000_000_000_000; // 5 trillion
export const CONTRACT_TEMPORAL_ACCELERATION_REWARD_STAMPS = 28;
export const CONTRACT_TEMPORAL_ACCELERATION_REWARD_RP = 1_200_000;

// Ultimate Challenge
export const CONTRACT_ULTIMATE_CHALLENGE_TARGET = 1_000_000_000_000; // 1 trillion
export const CONTRACT_ULTIMATE_CHALLENGE_TIME_LIMIT_SECONDS = 600; // 10 minutes
export const CONTRACT_ULTIMATE_CHALLENGE_UNLOCK_SHARDS = 5;
export const CONTRACT_ULTIMATE_CHALLENGE_UNLOCK_PRESTIGES = 20;
export const CONTRACT_ULTIMATE_CHALLENGE_REWARD_STAMPS = 25;
export const CONTRACT_ULTIMATE_CHALLENGE_REWARD_RP = 1_000_000;

// Beyond Infinity
export const CONTRACT_BEYOND_INFINITY_TARGET_LPS = 100_000_000_000;
export const CONTRACT_BEYOND_INFINITY_UNLOCK_SHARDS = 10;
export const CONTRACT_BEYOND_INFINITY_REWARD_STAMPS = 35;
export const CONTRACT_BEYOND_INFINITY_REWARD_RP = 2_000_000;
